services:
  ###> elasticsearch ###
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.0'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Pour désactiver la sécurité
    ports:
      - '9200:9200'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  ###< elasticsearch ###
