version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "3000:3000"  # Expose l'application sur le port 3000
    depends_on:
      - elasticsearch

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.0'
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"  # Expose Elasticsearch sur le port 9200
